sudo: required
language: python
python: "2.7"
addons:
    apt:
        packages:
            - libffi-dev
            - libjpeg-dev
            - libssl-dev
            - libtiff4-dev
            - libxml2-dev
            - libxslt1-dev
            - zlib1g-dev
services:
  - postgresql
  - redis-server
env: >
    DJANGO_SETTINGS_MODULE="conf_site.settings.testing"
before_install:
    - psql -c 'create database testing;' -U postgres
    - "pip install --upgrade pip"
install:
    - "pip install -r requirements/testing.txt"
script:
    - "flake8 --exclude=ansible,docs,migrations ."
    - "rstcheck --report warning docs/source/*.rst"
    - "./manage.py test"
