- name: install PostgreSQL packages
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - libpq-dev
    - postgresql
    - python-psycopg2

- name: create a PostgreSQL database for this project
  become: true
  become_user: postgres
  postgresql_db: name={{ django_database }}
                 encoding="UTF-8"
                 state=present
                 template=template0

- name: create a PostgreSQL user for this project
  become: true
  become_user: postgres
  postgresql_user: db={{ django_database }}
                   name={{ database_user }}
                   password={{ database_password }}
                   priv=ALL
                   role_attr_flags=CREATEDB
                   state=present
