- name: install aptitude
  apt: pkg=aptitude state=present
  become: true

- name: update package list & upgrade existing packages
  apt: update_cache=yes upgrade=yes cache_valid_time=3600
  become: true

- name: install common packages
  apt:
    name:
      - git
      - logrotate
      - ntp
      - python-pycurl
      - supervisor
      - unattended-upgrades
      - vim
    state: present
  become: true

- name: copy apt configuration file (20auto-upgrades)
  template: src=20auto-upgrades
            dest=/etc/apt/apt.conf.d/20auto-upgrades
  become: true

- name: copy apt configuration file (50unattended-upgrades)
  template: src=50unattended-upgrades
            dest=/etc/apt/apt.conf.d/50unattended-upgrades
  become: yes
