version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13-jessie
        environment:
           DJANGO_SETTINGS_MODULE: "conf_site.settings.testing"
           PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.6
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: testing
      - image: redis:3.2.6
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies.
      - restore_cache:
          keys:
          - v1-python-dependencies-{{ checksum "requirements/testing.txt" }}-{{ checksum "requirements/base.txt" }}
      - run:
          name: install dependencies
          command: |
            mkdir -p ~/venv
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements/testing.txt
      - save_cache:
          paths:
            - ~/venv
          key: v1-python-dependencies-{{ checksum "requirements/testing.txt" }}-{{ checksum "requirements/base.txt" }}
      - run:
          name: configure static files
          command: |
            . ~/venv/bin/activate
            ./manage.py collectstatic --noinput
      - run:
          name: run code linting
          command: |
            . ~/venv/bin/activate
            flake8 --exclude=ansible,docs,migrations .
      - run:
          name: run documentation linting
          command: |
            . ~/venv/bin/activate
            rstcheck --report warning docs/source/*.rst
      - run:
          name: run automated tests
          command: |
            . ~/venv/bin/activate
            python -Wall manage.py test
      - store_artifacts:
          path: test-reports
          destination: test-reports
