- name: bootstrap server for Ansible
  gather_facts: false
  hosts: production
  tasks:
    - import_tasks: tasks/bootstrap.yml
  vars:
    - deployment_user: pydata


- name: deploy to production servers
  hosts: production
  roles:
    - db
    - web
  vars_files:
    - group_vars/production
    - secrets.yml
